language: node_js
node_js:
  - "stable"
sudo: false
before_script:
  - export DISPLAY=:99.0  
  - sh -e /etc/init.d/xvfb start
script: "gulp ci"
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info
